  version: "3.9"

  services:
    site:
      image: 127.0.0.1:5000/cloudwingsliftup:latest   # troque REGISTRY_HOST (veja nota abaixo)
      networks:
        - network_swarm_public
      deploy:
        replicas: 1
        restart_policy:
          condition: any
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=network_swarm_public"

          # Router HTTPS
          - "traefik.http.routers.site.rule=Host(`site.cloudwings.com.br`)"
          - "traefik.http.routers.site.entrypoints=websecure"
          - "traefik.http.routers.site.tls=true"
          # 👉 use o NOME DO SEU RESOLVER exatamente como está no Traefik:
          - "traefik.http.routers.site.tls.certresolver=letsencrypt"
          # Porta interna do container (Nginx/Vite está servindo 80)
          - "traefik.http.services.site.loadbalancer.server.port=80"
          - "traefik.http.services.site.loadbalancer.passHostHeader=true"

          # Router HTTP -> HTTPS (opcional, mas recomendado)
          - "traefik.http.routers.site-redirect.rule=Host(`site.cloudwings.com.br`)"
          - "traefik.http.routers.site-redirect.entrypoints=web"
          - "traefik.http.routers.site-redirect.middlewares=redirect-to-https"
          - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  networks:
    network_swarm_public:
      name: network_swarm_public
      external: true
